name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
# env:
  # CSV_URL: "http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
  # TARGET_VAR: "quality"
  # ALPHA: 0.9
  # L1_RATIO: 0.9
  # RANDOM_STATE: 42
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      
      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Train Model
      - name: Train Model
        run: |
          python run_ml.py
          
      # Test Model
      - name: Test Model
        run: |
          pytest test_model.py
